# Generated by Django 4.2.7 on 2025-07-31 00:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
            },
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Sala de Chat', 'verbose_name_plural': 'Salas de Chat'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='rabbitmqconnection',
            options={'verbose_name': 'Conexão RabbitMQ', 'verbose_name_plural': 'Conexões RabbitMQ'},
        ),
        migrations.RemoveField(
            model_name='rabbitmqconnection',
            name='is_active',
        ),
        migrations.AddField(
            model_name='rabbitmqconnection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('system', 'Sistema')], default='text', max_length=10),
        ),
        migrations.AlterModelTable(
            name='chatroom',
            table='chat_rooms',
        ),
        migrations.AlterModelTable(
            name='message',
            table='messages',
        ),
        migrations.AlterModelTable(
            name='rabbitmqconnection',
            table='rabbitmq_connections',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='backend.user'),
        ),
    ]
